### ISSUE TITLE
新版本无法输出结果

### ISSUE THREAD

**Issue by FickoTEL** [BlackGlory/copycat#1]
这几天使用copy cat时发现剪贴板里完全没有内容，回头发现copy cat最近更新了一次，不知是否为新版本问题。
浏览器为Chrome，版本 55.0.2883.87 (64-bit)

**Comment by BlackGlory** [comment]
@FickoTEL 具体是哪个功能呢?

**Comment by BlackGlory** [comment]
我大概知道问题在哪了, 上次修bug的时候手贱"规范化"了代码, 结果造成很多功能失效, 现在更新了一个新版本1.1.2, 应该会在一小时后于Chrome商店上线, 这个新版本应该没问题.

**Comment by FickoTEL** [comment]
:thumbsup: :smile: :+1:
