### ISSUE TITLE
Bold italic text convertion to markdown error

### ISSUE THREAD

**Issue by Ynjxsjmh** [BlackGlory/copycat#19]
If there is a text _**with both bold and italic**_, Copycat will convert them to `***with both bold and italics***`. It should be `_**with both bold and italics**_` or `__*with both bold and italics*__` etc.

Test link: sentence `是对问题状态的定义和状态转移方程的定义。` in https://www.zhihu.com/question/23995189/answer/35324479

MD style: GFM
Copycat version: 2.4.2

**Comment by BlackGlory** [comment]
Duplicate of #3
