### ISSUE TITLE
[Feature] Can you please support Asciidoc?

### ISSUE THREAD

**Issue by ovigia** [BlackGlory/copycat#29]
hello,

is it possible to support Asciidoc and reStructuredText?

thanks in advance

**Comment by ovigia** [comment]
after reading about it in the webstore looks like it already supports those formats, but those do no seem to appear on my menu.

**Comment by BlackGlory** [comment]
Manifest V3 release will add basic support for AsciiDoc.
For reStructuredText, I don't plan to support it yet, because I can't even open [their online editor].

[their online editor]: http://rst.ninjs.org/
