### ISSUE TITLE
Nesting of emphasis

### ISSUE THREAD

**Issue by hxka** [BlackGlory/copycat#3]
In case of something like `<em><strong>strong</strong> in em</em>` Copycat produces `***strong** in em*` which some parsers (notably, Reddit) don't handle correctly. It doesn't help that `*` can be an indicator for a list. It seems like denoting outer emphasis with `_`'s instead of `*`'s, i.e. `_**strong** in em_` makes them parse this correctly. Can this be implemented?

**Comment by BlackGlory** [comment]
To solve this problem temporarily, it's simple, just add a Markdown flavor as a patch.

From a software engineering perspective, a better solution is to provide a UI that allows users to customize their own Markdown flavor, which is currently not in my plan.

**Comment by BlackGlory** [comment]
May allow user-defined turndown parameters in v3.0.0
