### ISSUE TITLE
Copy GIF

### ISSUE THREAD

**Issue by deadcoder0904** [BlackGlory/copycat#30]
This is a brilliant extension that just works.

I was wondering if it's possible to add GIF. Currently, I was trying to copy [this GIF](https://huvik.dev/improve-prototyping-speed-of-prisma/run-on-save-prisma.gif) but it only copied it as image in Windows.

Then I tried Copycat but it doesn't have support for GIF option. Any chances it could work?

**Comment by BlackGlory** [comment]
As far as I know, this is impossible: [copy-gif](https://github.com/BlackGlory/copy-gif).

**Comment by deadcoder0904** [comment]
Damn, didn't know you created this as well haha :)
