### ISSUE TITLE
Uncaught (in promise) [object Object]

### ISSUE THREAD

**Issue by askintution** [BlackGlory/copycat#39]
最近chrome更新之后，发现提示错误用不了了

Uncaught (in promise) [object Object]
上下文
_generated_background_page.html
堆叠追踪
browser-polyfill.min.js:1 (匿名函数)

**Comment by BlackGlory** [comment]
请告知一下Chrome版本号, 操作系统, 复现此错误的步骤.
我自己在Windows 10上的Chrome 99.0.4844.82上没有遇到问题.

**Comment by askintution** [comment]
我发现虽然报错，但还能用，就没管了
