### ISSUE TITLE
add option for custom context menu

### ISSUE THREAD

**Issue by Eronana** [BlackGlory/copycat#4]
thanks for this extension, it's the best extension used to copy as markdown.
so how about add these features:
- hide context menu
- only display one item(copy as markdown, copy as html, or other things we can configure) instead of current TWO level menu

**Comment by BlackGlory** [comment]
The ability to allow users to customize the menu structure requires a lot of code modification, so these requirements are not implemented for the time being.

**Comment by bugsysop** [comment]
You need only to modify these 2 lines in `turndown.d.ts`:
````
    emDelimiter?: '_'|'*'
    strongDelimiter?: '**'|'__'
````
Default for Turndown is set to `_` for emphasis and `**` for bold.
Ref.: https://github.com/domchristie/turndown#options

**Comment by BlackGlory** [comment]
@bugsysop d.ts suffix is a TypeScript type definition file, which does not affect the actual running code. In addition, the issue corresponding to this message seems to be https://github.com/BlackGlory/Copycat/issues/3.
