### ISSUE TITLE
【Bug】浏览器启动 Copycat 扩展右键菜单未生效

### ISSUE THREAD

**Issue by xianghongai** [BlackGlory/copycat#41]
如题，需要 Disable 一下重新启用才能生效。

- Firefox，Version 110

**Comment by BlackGlory** [comment]
很奇怪, 更像是Firefox的bug.

**Comment by xianghongai** [comment]
不清楚是不是 Manifest V3 相关问题

**Comment by BlackGlory** [comment]
Duplicate of #48, It should be fixed in v2.4.6.
