### ISSUE TITLE
Edge无法使用，右键菜单无相关菜单项

### ISSUE THREAD

**Issue by LeungGin** [BlackGlory/copycat#45]
Edge从插件商店下载并重启浏览器后，在右键菜单中未出现相关菜单项。

操作系统：macOS Catalina 10.15.7
Edge版本：111.0.1661.51 (正式版本) (x86_64)

插件安装详情截图
<img width="931" alt="image" src="https://user-images.githubusercontent.com/33046843/227415609-0ced2b11-6fb1-457b-977c-105c637eff25.png">

页面使用详情截图
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/33046843/227415817-e6d48f70-3016-498d-be26-fee73858083f.png">

**Comment by BlackGlory** [comment]
最近Chromium不知道更新了什么, 导致部分标签页注入内容脚本的速度特别慢.
Copycat创建右键菜单被排在注入内容脚本之后, 如果内容脚本没注入完, 菜单就不会创建, 所以你等个几分钟应该会看到菜单的.

等v3.0.2通过商店审核, 应该能修复此问题(不完全算得上是修复, 因为只是调换了顺序, 如果内容脚本没注入完, 一些功能没法正常使用), 如果v3.0.2还有问题, 再重新打开此问题.
等不及审核的话可以下载源代码然后用开发者模式载入: https://github.com/BlackGlory/copycat/releases/download/v3.0.2/dist.zip
