### ISSUE TITLE
[Feature Request] Support Paste Content of Clipboard as Pure Text

### ISSUE THREAD

**Issue by tjx666** [BlackGlory/copycat#47]
## Reason

I often copy some text from vscode and paste it to confference, but will also paste with css style. So, it would be convinnient to add a context menu item to paste the content of clipboard to pure text.

## Expect

Add a new menu item named `Paste Content of Clipboard as Pure Text`

**Comment by BlackGlory** [comment]
Don't browsers already provide this feature?

![image](https://github.com/BlackGlory/copycat/assets/1365962/dbce1da5-45cf-40c7-9144-000b56e71efe)

**Comment by tjx666** [comment]
Seems the `Paste and Match Style` is the same as `Paste as Plain Text

<img width="1208" alt="image" src="https://github.com/BlackGlory/copycat/assets/41773861/e821c185-77d6-4387-b526-c76a72701638">

**Comment by xianghongai** [comment]
此功能，推荐我的油猴脚本：https://greasyfork.org/zh-CN/scripts/448222-copy-it
