### ISSUE TITLE
[Feature Request] format selected content

### ISSUE THREAD

**Issue by tjx666** [BlackGlory/copycat#50]
For example github issue.

ref: https://prettier.io/docs/en/browser

**Comment by BlackGlory** [comment]
We already have this, what more do you need?

https://github.com/BlackGlory/copycat/blob/f6b59993d87d0b73ef350a82f3015a53f5f967eb/src/utils/format-html.ts#L4-L10

**Comment by BlackGlory** [comment]
Closed due to lack of meaningful information

**Comment by tjx666** [comment]
@BlackGlory I want this extension can format markdown content and it's code block. Just like I use prettier to format markdown in vscode.

**Comment by BlackGlory** [comment]
I wouldn't consider formatting code blocks at all, it's a classic maintenance pitfall. If you have a need for language-specific formatting, I suggest you maintain your own fork.

For Markdown itself, Copycat already provides some configuration items. prettier uses the same parser under the hood and doesn't seem to provide any more meaningful options.
