### ISSUE TITLE
Chrome latest version 120.0.6099.130 Copycat version 3.1.3 - not work bbcode

### ISSUE THREAD

**Issue by mod3m** [BlackGlory/copycat#52]
Has it stopped working only for me? Everything was still fine this afternoon, but it broke down in the evening. I think after the update. It partially works, partially doesn't. In particular, bbcode does not work

**Comment by BlackGlory** [comment]
v3.1.4 should fix this issue, it is pending review.
You can now install [v3.1.4] immediately via developer mode.

[v3.1.4]: https://github.com/BlackGlory/copycat/releases/download/v3.1.4/dist.zip
