### ISSUE TITLE
Hard to find when searching GitHub repos

### ISSUE THREAD

**Issue by huyz** [BlackGlory/copycat#54]
There are a lot of `copycat` projects on GitHub and finding this project is hard.

For example: https://github.com/search?q=copycat+chrome+extension&ref=opensearch&type=repositories

Perhaps adding `chrome extension` or `browser extension` to the project description would help.

**Comment by BlackGlory** [comment]
It's enough to be able to find it with Google.
No one takes Github's repository search engine seriously.
