### ISSUE TITLE
Feature Request: regex conversion custom copy?

### ISSUE THREAD

**Issue by ylluminate** [BlackGlory/copycat#56]
I'm finding use cases where I need to manipulate a certain set of attributes rather frequently and would like to convert them to another form of output that simplifies it over standard HTML or other options. Could you give us a custom option that will utilize a (or a series of) regular expression to reflow the copied content to a new format output for the pasteboard/clipboard?

**Comment by BlackGlory** [comment]
This requirement is more suitable to be implemented with AutoHotKey.

Example:
```ahk
#Persistent
OnClipboardChange("ClipChanged")
Return

ClipChanged() {
  result := RegExReplace(Clipboard, "(.*)", "$1$1")
  If result {
    Clipboard := result
    Sleep 500
  }
}
```

**Comment by ylluminate** [comment]
I get your point, but I would do it with TextSoap or Keyboard Maestro on macOS since we don't use Windows. I had hoped to consolidate this though since I was planning on sharing this with multiple team members who don't have quite as much experience and this would be much handier/useful for managing such a setup. 

Thanks anyway. 😿
